"""
Terraform Artifact Generation & Storage Service
Generates Terraform files for deployments and stores them in Azure Blob Storage
"""

import logging
import os
from typing import Dict, Any, Optional, List
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

TF_FILES = {
    "main.tf": """# Generated by InfraLift - {deployment_name}
# Timestamp: {timestamp}

terraform {{
  required_version = "~> 1.5"
  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }}
  }}
  backend "{backend_type}" {{
    {backend_config}
  }}
}}

provider "azurerm" {{
  features {{
    resource_group {{
      prevent_deletion_if_contains_resources = false
    }}
  }}
  subscription_id = "{subscription_id}"
}}

{resources}
""",
    "variables.tf": """# Generated by InfraLift - {deployment_name}
# Timestamp: {timestamp}

{variables}
""",
    "outputs.tf": """# Generated by InfraLift - {deployment_name}
# Timestamp: {timestamp}

{outputs}
""",
    "terraform.tfvars": """# Generated by InfraLift - {deployment_name}
# Timestamp: {timestamp}

{tfvars}
""",
}


class TerraformService:
    """Generate and store Terraform artifacts for deployments"""

    def __init__(self, redis_client=None):
        self.redis_client = redis_client

    def generate_main_tf(self, deployment: Dict[str, Any], backend_type: str = "azurerm") -> str:
        sub_id = deployment.get("subscriptionId", "00000000-0000-0000-0000-000000000000")
        rg = deployment.get("resourceGroup", "rg-default")
        sa = deployment.get("storageAccount", "infraliftterraform")
        container = deployment.get("containerName", "terraform-artifacts")
        key = f"deployments/{deployment.get('deploymentId', 'unknown')}/terraform.tfstate"

        backend_cfg = {
            "azurerm": f'storage_account_name = "{sa}"\n    container_name       = "{container}"\n    key                  = "{key}"\n    resource_group_name  = "{rg}"',
            "local": 'path = "terraform.tfstate"',
        }

        resources_tf = deployment.get("resources", "# No resources defined")
        name = deployment.get("resourceName", "infrastructure")

        return TF_FILES["main.tf"].format(
            deployment_name=name,
            timestamp=datetime.now(timezone.utc).isoformat(),
            backend_type=backend_type,
            backend_config=backend_cfg.get(backend_type, backend_cfg["local"]),
            subscription_id=sub_id,
            resources=resources_tf,
        )

    def generate_variables_tf(self, variables: List[Dict[str, str]]) -> str:
        lines = []
        for v in variables:
            desc = v.get("description", "")
            default_val = v.get("default", "")
            lines.append(f'variable "{v["name"]}" {{')
            if desc:
                lines.append(f'  description = "{desc}"')
            lines.append(f'  type        = {v.get("type", "string")}')
            if default_val:
                lines.append(f'  default     = "{default_val}"')
            lines.append("}")
            lines.append("")
        return "\n".join(lines) if lines else '# variable "example" {\n#   type = string\n# }\n'

    def generate_outputs_tf(self, outputs: List[Dict[str, str]]) -> str:
        lines = []
        for o in outputs:
            desc = o.get("description", "")
            lines.append(f'output "{o["name"]}" {{')
            lines.append(f'  value = {o.get("value", "azurerm_resource_group.main.id")}')
            if desc:
                lines.append(f'  description = "{desc}"')
            lines.append("}")
            lines.append("")
        return "\n".join(lines) if lines else '# output "resource_id" {\n#   value = azurerm_resource_group.main.id\n# }\n'

    def generate_tfvars(self, variables: Dict[str, Any]) -> str:
        lines = []
        for k, v in variables.items():
            if isinstance(v, str):
                lines.append(f'{k} = "{v}"')
            elif isinstance(v, bool):
                lines.append(f"{k} = {str(v).lower()}")
            else:
                lines.append(f"{k} = {v}")
        return "\n".join(lines)

    async def save_artifacts(self, deployment: Dict[str, Any], files: Dict[str, str]) -> Dict[str, Any]:
        """Save Terraform files - stores to both Redis metadata and Azure Blob if configured"""
        import os as env_os
        conn_str = env_os.getenv("STORAGE_CONNECTION_STRING", "")
        storage_path = f"deployments/{deployment.get('deploymentId', 'unknown')}/"

        saved = {}
        if conn_str:
            try:
                from azure.storage.blob import BlobServiceClient
                container = env_os.getenv("STORAGE_CONTAINER_NAME", "terraform-artifacts")
                blob_service = BlobServiceClient.from_connection_string(conn_str)
                container_client = blob_service.get_container_client(container)
                await container_client.create_container()  # no-op if exists

                for filename, content in files.items():
                    blob_path = f"{storage_path}{filename}"
                    blob_client = container_client.get_blob_client(blob_path)
                    blob_client.upload_blob(content, overwrite=True)
                    saved[filename] = f"https://{blob_service.account_name}.blob.core.windows.net/{container}/{blob_path}"
                    logger.info(f"Saved {blob_path} to Blob Storage")
            except Exception as e:
                logger.warning(f"Blob storage unavailable, saving locally: {e}")
                self._save_local(storage_path, files)
                saved = {f: f"local://{storage_path}{f}" for f in files}
        else:
            self._save_local(storage_path, files)
            saved = {f: f"local://{storage_path}{f}" for f in files}

        if self.redis_client:
            meta_key = f"terraform:{deployment.get('deploymentId', 'unknown')}"
            await self.redis_client.setex(
                meta_key, 86400 * 30,
                json.dumps({"deploymentId": deployment.get("deploymentId"), "files": saved, "savedAt": datetime.now(timezone.utc).isoformat()})
            )
        return saved

    def _save_local(self, path: str, files: Dict[str, str]):
        local_dir = os.path.join("terraform_artifacts", path)
        os.makedirs(local_dir, exist_ok=True)
        for filename, content in files.items():
            filepath = os.path.join(local_dir, filename)
            with open(filepath, "w") as f:
                f.write(content)
            logger.info(f"Saved locally: {filepath}")


terraform_service = TerraformService()

import json
